--=============================================
-- Author:		Margaret Horner
-- Create date: June 2021
-- Description:	Inpatients with Malnutrition Diagnosis
-- =============================================
USE CLARITY 
DECLARE @SERVAREAID VARCHAR(30) = '10' --REPLACE WITH SERVICE AREA ID
--DECLARE @STARTDATE SMALLDATETIME = DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE())-1, 0)
--DECLARE @ENDDATE  SMALLDATETIME = DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE())+0, 0);
--Declare @STARTDATE = '2019-07-01'
--Declare @ENDDATE = '2020-10-22'
;
SELECT
	MALNUTRITION.*,
	ISNULL(LEFT(PAT.PAT_MRN_ID, 25), '') 'Med_Rec_Num',
	ISNULL(PAT.PAT_NAME, '') 'Patient_Name',
	ISNULL(CONVERT(VARCHAR, PEH.HOSP_ADMSN_TIME, 101), '') 'Admit_Date',
	ISNULL(CONVERT(VARCHAR, PEH.HOSP_DISCH_TIME, 101), '') 'Disch_Date',
	ISNULL(DISPO.NAME, '') 'Discharge_Disposition',
	FLOOR((CAST (PEH.HOSP_ADMSN_TIME AS INTEGER) - CAST(PAT.BIRTH_DATE AS INTEGER)) / 365.25) [PATIENT AGE],
	CASE
		WHEN
			CAST(DATEDIFF(DD, PAT.BIRTH_DATE, PEH.HOSP_ADMSN_TIME) / 365.5 AS INT) >= 18 
		THEN
			'Adult' 
		WHEN
			CAST(DATEDIFF(DD, PAT.BIRTH_DATE, PEH.HOSP_ADMSN_TIME) / 365.5 AS INT) < 18 
		THEN
			'Pediatric' 
		ELSE
			'Unknown' 
	END
	AS 'Age Group' ,
	DATEDIFF(DD, PEH.HOSP_ADMSN_TIME, PEH.HOSP_DISCH_TIME) [LOS] ,
	EPM.PAYOR_NAME ,
	DRG.DRG_NUMBER , DRG.DRG_NAME ,
	APRDRG.[APR DRG NUMBER] ,
	APRDRG.[APR DRG NAME] 
FROM
	(
		SELECT DISTINCT
			ISNULL(CONVERT(VARCHAR, HA.HSP_ACCOUNT_ID), '') 'HAR_ID',
			ISNULL(LEFT(PAT.PAT_MRN_ID, 25), '') 'Med_Rec_Num',
			ISNULL(PAT.PAT_NAME, '') 'Patient_Name',
			ISNULL(CONVERT(VARCHAR, HA.CODING_DATETIME, 101), '') 'Coding_Complete_Date',
			ISNULL(CONVERT(VARCHAR, PEH.HOSP_ADMSN_TIME, 101), '') 'Admit_Date',
			ISNULL(CONVERT(VARCHAR, PEH.HOSP_DISCH_TIME, 101), '') 'Disch_Date',
			ISNULL(DISPO.NAME, '') 'Discharge_Disposition',
			CAST(DATEDIFF(DD, PAT.BIRTH_DATE, PEH.HOSP_ADMSN_TIME) / 365.5 AS INT) AS [PATIENT AGE],
			ZC_ACCT_CLASS_HA.NAME [ACCOUNT CLASS] 			--INTO #accts
,
			DX.LINE [DX LINE],
			EDG.CURRENT_ICD10_LIST [DX CODE],
			EDG.DX_NAME [DX DESCRIPTION],
			HA.PRIMARY_PAYOR_ID 
		FROM
			HSP_ACCOUNT HA 
			LEFT JOIN
				PAT_ENC_HSP PEH 
				ON PEH.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID 
			JOIN
				PATIENT PAT 
				ON PEH.PAT_ID = PAT.PAT_ID 
			JOIN
				VALID_PATIENT VP 
				ON PAT.PAT_ID = VP.PAT_ID 
				AND VP.IS_VALID_PAT_YN = 'Y' 
			LEFT JOIN
				ZC_DISCH_DISP DISPO 
				ON PEH.DISCH_DISP_C = DISPO.DISCH_DISP_C 
			JOIN
				HSP_ACCT_DX_LIST DX 
				ON HA.HSP_ACCOUNT_ID = DX.HSP_ACCOUNT_ID 
			JOIN
				CLARITY_EDG EDG 
				ON DX.DX_ID = EDG.DX_ID 
			LEFT JOIN
				ZC_ACCT_CLASS_HA 
				ON HA.ACCT_CLASS_HA_C = ZC_ACCT_CLASS_HA.ACCT_CLASS_HA_C 
		WHERE
			CAST(HA.CODING_DATETIME AS DATE) BETWEEN '2021-01-01' AND '2021-05-31' 			
			AND ha.SERV_AREA_ID = @SERVAREAID
			AND PEH.HOSP_DISCH_TIME IS NOT NULL 
			AND HA.ACCT_CLASS_HA_C = 101 			--AND peh.ADT_PAT_CLASS_C = 101
			AND HA.CODING_STATUS_C = 4 
			AND EDG.REF_BILL_CODE IN 
			(
				'E40',
				'E41',
				'E42',
				'E43',
				'E44',
				'E44.1',
				'E45',
				'E46' 
			)
	)
	MALNUTRITION 
	JOIN
		HSP_ACCOUNT HA 
		ON MALNUTRITION.HAR_ID = HA.HSP_ACCOUNT_ID 
	LEFT JOIN
		PAT_ENC_HSP PEH 
		ON PEH.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID 
	JOIN
		PATIENT PAT 
		ON PEH.PAT_ID = PAT.PAT_ID 
	JOIN
		VALID_PATIENT VP 
		ON PAT.PAT_ID = VP.PAT_ID 
		AND VP.IS_VALID_PAT_YN = 'Y' 
	LEFT JOIN
		ZC_DISCH_DISP DISPO 
		ON PEH.DISCH_DISP_C = DISPO.DISCH_DISP_C 
	LEFT JOIN
		CLARITY_EPM EPM 
		ON HA.PRIMARY_PAYOR_ID = EPM.PAYOR_ID 
	LEFT JOIN
		CLARITY_DRG DRG 
		ON HA.FINAL_DRG_ID = DRG.DRG_ID 		
	--left join HSP_ACCT_DX_LIST dx on ha.HSP_ACCOUNT_ID = dx.DX_ID
	--left join CLARITY_EDG edg on dx.DX_ID = edg.DX_ID
	LEFT JOIN
		(
			SELECT DISTINCT
				DRGS.HSP_ACCOUNT_ID,
				APRDRGS.DRG_NUMBER [APR DRG NUMBER],
				APRDRGS.DRG_NAME [APR DRG NAME] 
			FROM
				HSP_ACCT_MULT_DRGS DRGS 
				JOIN
					CLARITY_DRG APRDRGS 
					ON DRGS.DRG_ID = APRDRGS.DRG_ID 
					AND APRDRGS.DRG_CODE_SET_C = 3
		)
		APRDRG 
		ON HA.HSP_ACCOUNT_ID = APRDRG.HSP_ACCOUNT_ID 
WHERE
	CAST(HA.DISCH_DATE_TIME AS DATE) BETWEEN '2021-01-01' AND '2021-05-31' 
	AND HA.SERV_AREA_ID = @SERVAREAID 
	AND PEH.HOSP_DISCH_TIME IS NOT NULL 	
	--AND ha.ACCT_CLASS_HA_C = 101
	--AND peh.ADT_PAT_CLASS_C = 101
	AND HA.CODING_STATUS_C = 4