select 
ADMISSION_PROV_ID,
ser.PROV_NAME,
* 
from 
PAT_ENC_HSP peh
LEFT JOIN CLARITY_DEP dep on peh.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN CLARITY_SER ser on peh.ADMISSION_PROV_ID = ser.PROV_ID
where HOSP_ADMSN_TIME >= '1/1/2020' and HOSP_ADMSN_TIME < '1/1/2021'
and dep.DEPARTMENT_ID = '100000142'
