select 
	ACCESS_WRKF.USER_ID
	,emp.NAME
	,ACCESS_WRKF.METRIC_ID
	,logging.METRIC_NAME
	,ACCESS_WRKF.ACCESS_TIME
	,ACCESS_WRKF.WORKSTATION_ID
	,LAG(ACCESS_TIME,1) OVER (partition by ACCESS_WRKF.user_id,workstation_id order by access_time) previous_time
	FROM CLARITY.dbo.ACCESS_WRKF ACCESS_WRKF
	JOIN clarity.dbo.ACCESS_LOG_METRIC logging on ACCESS_WRKF.METRIC_ID = logging.METRIC_ID
	join CLARITY.dbo.CLARITY_EMP emp on access_wrkf.USER_ID = emp.USER_ID
	WHERE emp.USER_ID = '4968'  --'1171'
	AND (ACCESS_WRKF.ACCESS_TIME>={ts '2020-10-15 00:00:00'} AND ACCESS_WRKF.ACCESS_TIME<{ts '2021-01-19 00:00:00'}) 
	 AND (ACCESS_WRKF.METRIC_ID=14010 OR ACCESS_WRKF.METRIC_ID=14011 
			OR ACCESS_WRKF.METRIC_ID=14020 OR ACCESS_WRKF.METRIC_ID=14030 OR ACCESS_WRKF.METRIC_ID=14050)
order by ACCESS_TIME


--select * from CLARITY.dbo.CLARITY_EMP where name like '%boroz%' -- user_id = '305180'

