CREATE OR ALTER       PROCEDURE [OH].[40061_VRWR_SUPPLY_REV_AND_USAGE] 

@ExtDateBegin	VARCHAR(10)
, @ExtDateEnd	VARCHAR(10)


AS 
BEGIN 
SET NOCOUNT ON 

DECLARE 
	@DateBegin	VARCHAR(20)
	, @DateEnd	VARCHAR(20)


SET	@DateBegin = EPIC_UTIL.EFN_DIN(@ExtDateBegin) 
SET @DateEnd   = EPIC_UTIL.EFN_DIN(@ExtDateEnd) ;


SELECT		CLARITY_EAP.PROC_CODE
			, OR_SPLY.PRIMARY_EXT_ID				LAWSON_NUMBER
			, OR_SPLY.SUPPLY_ID
			, OR_SPLY.SUPPLY_NAME
			, ALIAS.ALIAS
			, CL_COST_CNTR.COST_CENTER_CODE
			, CL_COST_CNTR.COST_CENTER_NAME
			, OR_LOC.LOC_ID							SUPPLY_LOCATION_ID
			, LOC.LOC_NAME							SUPPLY_LOCATION_NAME
			, SUM(CASE 
					WHEN HSP_ACCOUNT.ACCT_BASECLS_HA_C = 1 
						THEN HSP_TRANSACTIONS.QUANTITY
					ELSE 0 END )				IP_QUANTITY
			, SUM(CASE 
					WHEN HSP_ACCOUNT.ACCT_BASECLS_HA_C = 1 
						THEN HSP_TRANSACTIONS.TX_AMOUNT
					ELSE 0 END )				IP_REVENUE
			, SUM(CASE 
					WHEN HSP_ACCOUNT.ACCT_BASECLS_HA_C > 1
						THEN HSP_TRANSACTIONS.QUANTITY
					ELSE 0 END )				OP_QUANTITY
			, SUM(CASE 
					WHEN HSP_ACCOUNT.ACCT_BASECLS_HA_C > 1
						THEN HSP_TRANSACTIONS.TX_AMOUNT
					ELSE 0 END )				OP_REVENUE
			, SUM(HSP_TRANSACTIONS.TX_AMOUNT)	TOTAL_REVENUE
			, SUM(HSP_TRANSACTIONS.QUANTITY)	TOTAL_QUANTITY

FROM		HSP_TRANSACTIONS
			LEFT JOIN 
				CL_COST_CNTR
				ON HSP_TRANSACTIONS.COST_CNTR_ID = CL_COST_CNTR.COST_CNTR_ID
			LEFT JOIN 
				HSP_ACCOUNT
				ON HSP_TRANSACTIONS.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID
			LEFT JOIN 
				OR_SPLY
				ON HSP_TRANSACTIONS.SUP_ID = OR_SPLY.SUPPLY_ID
			LEFT JOIN 
				CLARITY_EAP
				ON HSP_TRANSACTIONS.PROC_ID = CLARITY_EAP.PROC_ID
			LEFT JOIN OR_SPLY_ALIAS ALIAS ON HSP_TRANSACTIONS.SUP_ID = ALIAS.ITEM_ID AND ALIAS.LINE = 1 
			LEFT JOIN CLARITY_DEP DEP ON HSP_TRANSACTIONS.DEPARTMENT = DEP.DEPARTMENT_ID
			LEFT JOIN OR_LOC ON HSP_TRANSACTIONS.PLACE_OF_SVC_ID = OR_LOC.LOC_ID
			LEFT JOIN CLARITY_LOC LOC ON OR_LOC.LOC_ID = LOC.LOC_ID 

WHERE		CAST(HSP_TRANSACTIONS.TX_POST_DATE AS DATE) >=	@DateBegin 
			AND CAST(HSP_TRANSACTIONS.TX_POST_DATE AS DATE) <= @DateEnd
			AND HSP_TRANSACTIONS.SUP_ID IS NOT NULL
			AND OR_SPLY.SUPPLY_NAME IS NOT NULL

GROUP BY	CLARITY_EAP.PROC_CODE
			, OR_SPLY.PRIMARY_EXT_ID				
			, OR_SPLY.SUPPLY_ID
			, OR_SPLY.SUPPLY_NAME
			, CL_COST_CNTR.COST_CENTER_CODE
			, CL_COST_CNTR.COST_CENTER_NAME
			, ALIAS.ALIAS
			, OR_LOC.LOC_ID
			, LOC.LOC_NAME

; END
